# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-28 01:50
from __future__ import unicode_literals

import applications.music.models
import applications.music.models_utils
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', applications.music.models_utils.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', applications.music.models_utils.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=30)),
                ('artist_name', models.CharField(max_length=30)),
                ('nb_title', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('birth_date', models.DateField(default='1995-01-01')),
                ('image', models.ImageField(blank=True, null=True, upload_to=applications.music.models.upload_to)),
            ],
            options={
                'verbose_name_plural': 'Albums',
                'verbose_name': 'Album',
            },
        ),
    ]
