# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-01 15:33
from __future__ import unicode_literals

import applications.blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to=applications.blog.models.upload_to),
        ),
    ]
